# Generated by Django 4.2.2 on 2023-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteplus', '0002_sharednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednote',
            name='title',
            field=models.CharField(default='Shared Note', max_length=200),
        ),
    ]
